# Generated by Django 3.0.5 on 2020-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('group', models.ManyToManyField(blank=True, related_name='groups', to='groups.Group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EAI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eai_code', models.IntegerField(unique=True)),
                ('app', models.ManyToManyField(to='cmdb.Application')),
            ],
            options={
                'ordering': ['eai_code'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('os_type', models.CharField(blank=True, choices=[('linux', 'Linux'), ('windows', 'Windows'), ('aix', 'Aix')], max_length=10)),
                ('domain', models.CharField(blank=True, choices=[('metnet', 'Metnet'), ('met_intnet', 'Met Intnet'), ('alicocorp', 'Alicocorp')], max_length=10)),
                ('environment', models.CharField(blank=True, choices=[('Dev', 'Dev'), ('Int', 'Int'), ('QA', 'Qa'), ('Prod', 'Prod'), ('DR', 'Dr'), ('Test', 'Test')], max_length=10)),
                ('app', models.ManyToManyField(blank=True, related_name='apps', to='cmdb.Application')),
                ('eai', models.ManyToManyField(blank=True, related_name='eais', to='cmdb.EAI')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
