# Generated by Django 3.0.5 on 2020-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eai',
            name='app',
            field=models.ManyToManyField(related_name='app', to='cmdb.Application'),
        ),
    ]
