# Generated by Django 3.0.5 on 2020-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('cmdb', '0002_auto_20200511_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='apps', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='eai',
            name='app',
            field=models.ManyToManyField(related_name='eais', to='cmdb.Application'),
        ),
        migrations.AlterField(
            model_name='server',
            name='app',
            field=models.ManyToManyField(blank=True, related_name='servers', to='cmdb.Application'),
        ),
        migrations.AlterField(
            model_name='server',
            name='eai',
            field=models.ManyToManyField(blank=True, related_name='servers', to='cmdb.EAI'),
        ),
    ]
